apiVersion: apps/v1
kind: Deployment
metadata:
  name: config-watcher
  labels:
    app: config-watcher
spec:
  replicas: 1
  selector:
    matchLabels:
      app: config-watcher
  template:
    metadata:
      labels:
        app: config-watcher
    spec:
      containers:
      - name: config-watcher
        image: config-watcher:v1
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
data:
  movie: lotr-the-two-towers
  show: rings-of-power
  test: "true"
  env: staging
